version: '3'
services:
  react:
    build:
      context: .
      dockerfile: ./docker/dev/react/Dockerfile
    volumes:
      - .:/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
